[package]
name = "Cinyras"
version = "0.0.1"
authors = [ "PryosCode <info@pryoscode.net>" ]
description = ""
repository = "https://github.com/PryosCode/Cinyras"
license = "Apache License 2.0"
license-file = "LICENSE"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
