name: Build

on:
  push:
    branches:
    - master

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cargo
      run: |
        cargo build --release
        echo "CARGO_VERSION=$(cat Cargo.toml | grep -m 1 'version =' | cut -d '"' -f 2)" >> $GITHUB_ENV
        mv target/release/cinyras cinyras-linux
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: cinyras-linux
        tag_name: v${{ env.CARGO_VERSION }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cargo
      run: |
        cargo build --release
        mv target/release/cinyras cinyras-windows
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: cinyras-windows
        tag_name: v${{ env.CARGO_VERSION }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cargo
      run: |
        cargo build --release
        mv target/release/cinyras cinyras-macos
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: cinyras-macos
        tag_name: v${{ env.CARGO_VERSION }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}