name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cargo
      run: |
        cargo build --release
        mv target/release/cinyras.exe cinyras-windows.exe
        echo CARGO_VERSION=$(cinyras-windows.exe -V | cut -d ' ' -f 2) >> $GITHUB_ENV
    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: cinyras-windows.exe
        tag_name: v${{ env.CARGO_VERSION }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cargo
      run: |
        cargo build --release
        mv target/release/cinyras cinyras-macos
        echo CARGO_VERSION=$(cinyras-linux -V | cut -d ' ' -f 2) >> $GITHUB_ENV
    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: cinyras-macos
        tag_name: v${{ env.CARGO_VERSION }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux:
    name: Linux
    runs-on: ubuntu-latest
    needs: [ windows, macos ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo
        run: |
          cargo build --release
          mv target/release/cinyras cinyras-linux
          echo CARGO_VERSION=$(cinyras-linux -V | cut -d ' ' -f 2) >> $GITHUB_ENV
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: cinyras-linux
          tag_name: v${{ env.CARGO_VERSION }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}