name: Rust

on:
  push:
    branches:
    - master

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions-rs/toolchain@v1 
    - name: Build
      run: cargo build --release
