name: Build

on:
  push:
    branches:
    - master

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cargo
      run: cargo build --release

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cargo
      run: cargo build --release

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cargo
      run: cargo build --release