name: Linux

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: |
          make
          mv cinyras cinyras-linux
          echo VERSION=$(./cinyras-linux -V | cut -d ' ' -f 2) >> $GITHUB_ENV
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: cinyras-linux
          tag_name: v${{ env.VERSION }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}