name: Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: |
          make
          mv cinyras cinyras-linux
          echo VERSION=$(./cinyras-linux -V | cut -d ' ' -f 2) >> $GITHUB_ENV
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: cinyras-linux
          tag_name: v${{ env.VERSION }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: pryoscode
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: |
            pryoscode/cinyras:latest
            pryoscode/cinyras:${{ env.VERSION }}