name: Windows

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Dependencies
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install curl
    - name: Make
      run: |
        make
        mv cinyras.exe cinyras-windows.exe
        echo VERSION=$(./cinyras-windows.exe -V | cut -d ' ' -f 2) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: cinyras-windows.exe
        tag_name: v${{ env.VERSION }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}